### ISSUE TITLE
Missing onoff capability

### ISSUE THREAD

**Issue by frodeheg** [osohotwateriot/no.osoincharge#2]
Can you please add an onoff capability?

This request has multiple reasons:
* The onoff status will immediately be visible on the device icon
* The timeline will then automatically show when on/off was called and from which source.
* It is more difficult to turn on/off using flows than to click the device icon
* Other apps that seek to control power usage (such as [Piggybank](https://github.com/frodeheg/no.sparegris)) is unable to control other devices by using flows. They can only set and read capabilities.

**Comment by osohotwateriot** [comment]
Hello,

The turn on/off functionality (flows) for the OSO Energy heaters manages the heating elements and forces the heater to heat the water or prevents it from doing that. The heaters themselves cannot be turned on or off.
Of course there is some limitations on these actions - if the temperature is below the minimum then the heating elements cannot be turned off and if it is equal to the maximum it will not be able to force it to heat the water.

With that in mind I will implement the onoff capability with the option to turn on/off the heating elements of the water heater for one hour - after that time has passed or the minimum/maximum temperature is reached the heater will go back to its normal state and resume control according to the current target temperature.

**Comment by osohotwateriot** [comment]
There is no mechanism to do a complete turn off of the water heater.
The API provides only ways to manage modes on the device like setting Sleep Mode when going on vacation or preventing it from heating the water with the Turn off action flow for one hour or until the temperature has reached the minimum.

There are also safety mechanisms in place for a minimum quantity of mixed water that the heater needs to maintain at all time which will automatically turn it on. The case is the same for the Legionella guard.

Using Sleep mode and High demand does not seem fine for the onoff capability:
- Sleep mode sets a lower temperature on the device but it will still turn on if that temperature is above the current temperature of the water. Also a period needs to be defined for the duration of that mode which cannot be done from the capability.
- High demand activated for 24 hours which will force the water heater to heat the water so it is always near the maximum and will increase the power consumption of the device - this is not something all users will want.

The best way to implement the functionality for now is to simply prevent the water heater from heating the water for one hour.
Setting it for more than an hour would mean that the heater will reach the minimum temperature and will continue to work normally from that point.
That way other applications can manage the water heater state - if needed they can set it on demand whenever they see that the current state is on.

I can see that Piggybank manages the consumption hourly due to the tariffs in Norway. This means that turning the heater off for one hour to avoid a big hourly consumption should be fine with this implementation.

The implementation is done in version 1.0.5 and is currently awaiting for certification.

**Comment by frodeheg** [comment]
Are you sure?
According to the [swagger](https://api.osoenergy.no/water-heater-api-swagger/index.html) there are two endpoints to use for turning on and off:
/1/Device/{deviceId}/TurnOn
/1/Device/{deviceId}/TurnOff

I don't see any information in the swagger that indicates that it will only last for one hour?

**Comment by osohotwateriot** [comment]
Yes. 
Those two endpoints have the fullUtilizationParam which is used to specify if the heater should be on/off for one hour (false) or until min/max temperature is reached (true).
Those are the apis used to implement the onoff capability.

The new version is released.

**Comment by frodeheg** [comment]
Does this also apply if you use the
'/1/Device/{deviceId}/OptimizationMode' - interface to set OptimizationOptions to 2 (Third Party)

I would guess such a setting would disable the internal overrides?

**Comment by osohotwateriot** [comment]
The optimization mode is a mechanism to manage the target temperature of the water heater.
When Auto - the electicity prices are used to optimize the consumption of the device.
When Third Party - no automatic optimization will be done on the device target temperature and control will be left to the third party application. In this case homey will set the target temperature and it will not be overriden unles the user activates High Demand or Sleep mode.
In general the optimization mode is not a way to manage the onoff state of the device but it will disable the override of the target temperature if you choose Off or Third party.

**Comment by osohotwateriot** [comment]
The heaters can be controlled by other third party applications (e.g. Home Assistant) and I don't think that all users will want to disable the Auto optimization mode on their devices since that already optimizes the device against the electricity prices.

If it is for managing the tariff of the household then the current implementation should work fine for 15 minute intervals well - there is no limit on calling the turn on/off of the heater every 15 minutes to manage the power consumption of the device. If the device is already turned off then it can be turned on with the other api to enable heating. If no action is executed then after one hour the device will continue working according to the selected optimization mode or target temperature so it really depends on the use case. A user can call the api to turn off the heater every 15 minutes which would extend that 1 hour with each command but the command will be rejected when the temperature drops below minimum as at least some quantity of hotwater needs to remain avalable at all time. These commands force the heater to remain in a certain state (on or off) for one hour but can be overriden with the opposite command.

Setting the temperature to the minimum and then reverting it back would defeat the purpose of running any optimizations on the device and it would still turn on if the minimum quantity of mixed water at 40 degrees C drops as this is a guarantee that the users have some quantity of hotwater.

If a user wants to have the heater remain off or reduce the power consumption in cases when they go on vacation for a bigger period of time then the user can always activate Sleep mode which will override the minimum quantity of hotwater needed for the device and set the minimum target temperature but that is not applicable when controlling the heater for short periods of time like the management of the tariffs.

**Comment by osohotwateriot** [comment]
There is a timer that makes an api call ro requenst data for the devices every 30 seconds and update the capabilities.
You can see the syncInterval in app.ts

**Comment by frodeheg** [comment]
Ah, sorry, I didn't see that one, well, great then :-)

**Comment by osohotwateriot** [comment]
If there is nothing more I will close the issues after some time, or you can do that also :)

**Comment by frodeheg** [comment]
There is just one thing I wonder about.
If you set the temperature I see the API endpoint set it for all 24 hours.
Does this also revert to some internal "optimization" setting after 1 hour / next hour, or does it always follow the plan?
....or does it apply deltas to the plan you submitted where the deltas are selected based on the price?

**Comment by osohotwateriot** [comment]
The API changes the current profile of the device.
This means that until the next optimization is run or sleep mode/high demand is activated the profile will remain the same as the one passed to the API - this can be for an hour or even more.
If the temperature is overriden it will be updated from the next sync.

The optimization should take place twice per day - in the afternoon and at midnight so the override will take some time before it is applied over the temperature set from Homey.
Of cource if the optimization mode is off then the profile should remain the same and the temperature will not change until a new temperature is selected from Homey.

It is always possible to do another change of the target temperature after it has been overriden by the optimization.

**Comment by frodeheg** [comment]
Thanks
